### PR TITLE
feat(frontend): persisted palette and dynamic favicon

### PR DESCRIPTION
**Pull request by JoshWannaPaas**
I utilized local storage with Recoil atom in 'recoil/palette.ts' to have the chosen palette persist upon entering the site.

Additionally, I created a new favicon for the site, and have made various icons that match the different palettes. This also comes with the functionality of dynamically changing the icon upon selecting different palettes.

image
image

### CODE REVIEW

**Review by tomiyee — APPROVED** [review]
Merge the other PR before this one.

Since this was independent from the other PR, you could have also made this branch off of main instead of off the centralized Ensemble PR. This would allow you to merge them independently instead of forcing to wait one before the other.

**Comment by tomiyee** [comment]
To elaborate, I ask you merge the other PR before this one is because this PR contains the changes in the other. If you merge this one first, you are capturing two PRs in one merge commit, which is not as clear and lead to the other PR becoming useless.

**Comment by tomiyee** [comment]
Thank you for the screenshots by the way.

**Comment by JoshWannaPaas** [comment]
> Merge the other PR before this one.
> 
> Since this was independent from the other PR, you could have also made this branch off of main instead of off the centralized Ensemble PR. This would allow you to merge them independently instead of forcing to wait one before the other.

Fairly certain this is a branch off of main. I'm not sure if it's shown otherwise? The files changed should also be dependent of everything else so I'm not sure how a mixup happened.

**Comment by tomiyee** [comment]
You are right

**Pull request merged**
